In [35]:
from google.colab import drive
drive.mount('/content/drive')
#1
import numpy as np
import pandas as pd
#関数化
def read_excel():
    #エクセル読み込み
    #df =pd.read_excel('ma_iden.xlsm',sheet_name='Sheet1', index_col=[0,1,2])
    #df =pd.read_excel("/content/drive/MyDrive/Colab Notebooks/iden/ma_iden.xlsm",sheet_name="Sheet1")
    df =pd.read_excel("/content/drive/MyDrive/Colab Notebooks/iden/ma_iden.xlsm ",sheet_name="Sheet1")
    #ExcelファイルをDataFrameに読み込む
    #df = pd.read_excel("date_2020.xlsx")

    #dfのほしい場所だけ抜き取る
    df=df.iloc[2:37,0:34]
    df
    #エラー値を０に変換
    df=df.fillna(0)
    #df
    #希望休（◎）を2へ変換
    df=df.replace('◎',2)
    #数値以外インデックスに使えない
    #df=df.replace({'日':16,'月':10,'火':11,'水':12,'木':13,'金':14,'土':15})
    columns_kiso=df.iloc[0,0:32].reset_index(drop=True)
    #df
    #休日数のテーブルを取得
    holiday=df.iloc[2:,33:34].reset_index(drop=True)
    holiday.columns=['休日数']
    #holiday
    #基礎テーブルを取得
    #df_i = df.set_index(columns_kiso)
    #date_columns_index = columns
    kiso_moto=df.iloc[1:,0:32].reset_index(drop=True)
    #kiso_moto=kiso_moto.loc[:,columns_kiso]
    #kiso_moto.columns=[i+1 for i in range(len(kiso_moto.columns))]
    #kiso_moto = pd.DataFrame(kiso_moto, columns=columns_moto)
    #kiso.columns=[i+1 for i in range(len(kiso.columns))]
    kiso_moto.columns=columns_kiso
    kiso=kiso_moto.drop(['土', '日'],axis=1)
    #kiso
    #return kiso_moto,holiday,kiso
    return kiso,holiday
    #return holiday,kiso

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
#エクセル読み込み
#kiso_moto,holiday,kiso=read_excel()
#holiday,kiso=read_excel()
kiso,holiday=read_excel()

In [3]:
#列リセット
sh=kiso.shape
kiso.columns=range(sh[1])
kiso

0   1                    2                    3   \
0           品　番  番号  2023-06-01 00:00:00  2023-06-02 00:00:00   
1     F81140146   1                    0                    0   
2     F81140146   2                    0                    0   
3     F81140146   3                    0                    0   
4     ZE1912020   1                    0                    0   
5     ZE1912020   2                    0                    0   
6     ZE1912020   3                    0                    0   
7     ZE1912020   4                    0                    0   
8     ZE1912020   5                    0                    0   
9     ZE1912020   6                    0                    0   
10    ZE1912020   7                    0                    0   
11   ZE1325820A   1                    0                    0   
12   ZE1325820A   2                    0                    0   
13   ZE1325820A   3                    0                    0   
14   ZE1325820A   4                    0                    0   
15   ZE1325820A   5                    0                    0   
16    ZE1325820   1                    0                    0   
17    ZE1325820   2                    0                    0   
18    ZE1325820   3                    0                    0   
19    ZE1325820   4                    0                    0   
20    ZE1325820   5                    0                    0   
21  16204C49450   1                    0                    0   
22  16204C49450   2                    0                    0   
23  16204C49450   3                    0                    0   
24   EG52371351   1                    0                    0   
25      EAUE006   1                    0                    0   
26      EAUE006   2                    0                    0   
27      EAUE006   3                    0                    0   
28      EAUE006   4                    0                    0   
29      EAUE006   5                    0                    0   
30    BPE814243   1                    0                    0   
31    BPE814243   2                    0                    0   
32    BPE814243   3                    0                    0   
33    BPE814243   4                    0                    0   

                     4                    5                    6   \
0   2023-06-05 00:00:00  2023-06-06 00:00:00  2023-06-07 00:00:00   
1                     0                    0                    0   
2                     0                    0                    0   
3                     0                    0                    2   
4                     0                    0                    0   
5                     0                    0                    0   
6                     0                    0                    0   
7                     0                    0                    0   
8                     0                    0                    0   
9                     0                    0                    0   
10                    0                    0                    0   
11                    0                    0                    0   
12                    0                    0                    0   
13                    0                    0                    0   
14                    0                    0                    0   
15                    0                    0                    0   
16                    0                    0                    0   
17                    0                    0                    0   
18                    0                    0                    0   
19                    0                    0                    0   
20                    0                    0                    0   
21                    0                    0                    0   
22                    0                    0                    0   
23                    0                    0                    0   
24          

In [4]:
kiso.reset_index(drop=True)

0   1                    2                    3   \
0           品　番  番号  2023-06-01 00:00:00  2023-06-02 00:00:00   
1     F81140146   1                    0                    0   
2     F81140146   2                    0                    0   
3     F81140146   3                    0                    0   
4     ZE1912020   1                    0                    0   
5     ZE1912020   2                    0                    0   
6     ZE1912020   3                    0                    0   
7     ZE1912020   4                    0                    0   
8     ZE1912020   5                    0                    0   
9     ZE1912020   6                    0                    0   
10    ZE1912020   7                    0                    0   
11   ZE1325820A   1                    0                    0   
12   ZE1325820A   2                    0                    0   
13   ZE1325820A   3                    0                    0   
14   ZE1325820A   4                    0                    0   
15   ZE1325820A   5                    0                    0   
16    ZE1325820   1                    0                    0   
17    ZE1325820   2                    0                    0   
18    ZE1325820   3                    0                    0   
19    ZE1325820   4                    0                    0   
20    ZE1325820   5                    0                    0   
21  16204C49450   1                    0                    0   
22  16204C49450   2                    0                    0   
23  16204C49450   3                    0                    0   
24   EG52371351   1                    0                    0   
25      EAUE006   1                    0                    0   
26      EAUE006   2                    0                    0   
27      EAUE006   3                    0                    0   
28      EAUE006   4                    0                    0   
29      EAUE006   5                    0                    0   
30    BPE814243   1                    0                    0   
31    BPE814243   2                    0                    0   
32    BPE814243   3                    0                    0   
33    BPE814243   4                    0                    0   

                     4                    5                    6   \
0   2023-06-05 00:00:00  2023-06-06 00:00:00  2023-06-07 00:00:00   
1                     0                    0                    0   
2                     0                    0                    0   
3                     0                    0                    2   
4                     0                    0                    0   
5                     0                    0                    0   
6                     0                    0                    0   
7                     0                    0                    0   
8                     0                    0                    0   
9                     0                    0                    0   
10                    0                    0                    0   
11                    0                    0                    0   
12                    0                    0                    0   
13                    0                    0                    0   
14                    0                    0                    0   
15                    0                    0                    0   
16                    0                    0                    0   
17                    0                    0                    0   
18                    0                    0                    0   
19                    0                    0                    0   
20                    0                    0                    0   
21                    0                    0                    0   
22                    0                    0                    0   
23                    0                    0                    0   
24          

In [5]:
date_columns_index = print(kiso.columns)

RangeIndex(start=0, stop=24, step=1)


In [6]:
##数値以外インデックスに使えない
#kiso_moto.iloc['土']
kiso.iloc[11]

0     ZE1325820A
1              1
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0
10             0
11             0
12             0
13             0
14             0
15             0
16             0
17             0
18             0
19             0
20             0
21             0
22             0
23             0
Name: 11, dtype: object

In [7]:
#kiso_moto['4']
kiso.columns[11]

11

In [8]:
len(kiso.columns)

24

In [9]:
holiday=holiday.reset_index(drop=True)
holiday

休日数
0    9
1    8
2    9
3    8
4    9
5    9
6   10
7    8
8    9
9    9
10   8
11   9
12   8
13   9
14   9
15  10
16   8
17   9
18   9
19   8
20   9
21   8
22   9
23   9
24  10
25   8
26   9
27  10
28   8
29   9
30  10
31   8
32   9

In [10]:
#2

def first_gene(kiso,holiday):
    #1か月の日数
    days=len(kiso.columns)-2
    #days=int(len(kiso.columns))-2
    #days

    #基礎テーブルのコピー
    kiso_copy=kiso.copy()
    #工場用追加
    holiday=holiday.reset_index(drop=True)
    holiday

    #行リセット
    kiso_copy=kiso_copy.iloc[1:,2:]
    kiso_copy=kiso_copy.reset_index(drop=True)
    kiso_copy

    #列リセット
    sh=kiso_copy.shape
    kiso_copy.columns=range(sh[1])
    kiso_copy

    for k in range(len(kiso_copy)):

        #休日を入れる変数
        h=[]
        #休日数だけループ
        while len(h)<holiday.loc[k][0]:
        #while len(h)<int(holiday.loc[k][0],base=10):
      #      n=np.random.randint(1,days+1)
            n=np.random.randint(1,days-2)
            if not n in h:
                h.append(n)

        #休日を埋め込む
        for i in h:
            if kiso_copy.loc[k][i]==0:
                kiso_copy.loc[k][i]=1
    return kiso_copy

In [11]:
days=len(kiso.columns)-2
x=np.random.randint(1,days-2,8)
x

array([ 9,  3, 10,  4, 19,  9, 14, 13])

In [12]:
holiday

休日数
0    9
1    8
2    9
3    8
4    9
5    9
6   10
7    8
8    9
9    9
10   8
11   9
12   8
13   9
14   9
15  10
16   8
17   9
18   9
19   8
20   9
21   8
22   9
23   9
24  10
25   8
26   9
27  10
28   8
29   9
30  10
31   8
32   9

In [13]:
#1か月の日数
days=len(kiso.columns)-2
#days=int(len(kiso.columns))-2
#days

#基礎テーブルのコピー
kiso_copy=kiso.copy()
#工場用追加
holiday=holiday.reset_index(drop=True)
holiday

#行リセット
kiso_copy=kiso_copy.iloc[1:,2:]
kiso_copy=kiso_copy.reset_index(drop=True)
kiso_copy

#列リセット
sh=kiso_copy.shape
kiso_copy.columns=range(sh[1])
kiso_copy

for k in range(len(kiso_copy)):

    #休日を入れる変数
    h=[]
    #休日数だけループ
    while len(h)<holiday.loc[k][0]:
    #while len(h)<int(holiday.loc[k][0]):
  #      n=np.random.randint(1,days+1)
        n=np.random.randint(1,days-2)
        if not n in h:
            h.append(n)

    #休日を埋め込む
    for i in h:
        if kiso_copy.loc[k][i]==0:
            kiso_copy.loc[k][i]=1
kiso_copy

0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15 16 17 18 19 20 21
0   0  1  1  0  0  0  0  1  0  0  ...  1  0  0  0  1  1  1  0  0  0
1   0  1  0  1  1  1  0  0  1  0  ...  0  1  0  0  0  1  0  0  0  0
2   0  0  0  1  2  1  0  1  1  1  ...  0  1  1  1  0  0  0  1  0  0
3   0  0  1  0  1  1  0  0  0  1  ...  1  0  0  0  1  1  1  0  0  0
4   0  1  1  1  0  0  0  1  0  1  ...  1  0  1  1  0  0  1  0  0  0
5   0  0  0  0  0  1  1  1  0  0  ...  0  1  0  1  1  1  0  0  0  0
6   0  1  0  0  0  0  1  1  1  1  ...  0  0  0  0  0  1  1  1  0  0
7   0  0  1  0  0  0  1  1  0  0  ...  0  0  0  0  1  1  1  0  0  0
8   0  0  0  1  0  1  0  1  1  1  ...  0  0  0  0  1  1  0  0  0  0
9   0  0  0  0  1  0  0  2  1  0  ...  1  1  1  0  0  1  1  1  0  0
10  0  1  0  0  1  1  1  0  1  0  ...  1  1  0  0  0  1  0  0  0  0
11  0  0  1  0  0  0  1  0  1  0  ...  1  0  0  0  1  1  1  1  0  0
12  0  0  1  1  1  0  0  0  0  1  ...  1  0  0  1  0  0  0  1  0  0
13  0  0  1  0  1  0  1  0  0  0  ...  1  1  0  0  0  1  1  1  0  0
14  0  1  1  0  1  0  0  2  0  1  ...  0  0  0  0  1  0  1  1  0  0
15  0  1  0  0  1  0  1  1  1  1  ...  1  0  0  0  0  0  0  1  0  0
16  0  0  0  1  1  0  0  0  0  0  ...  1  0  1  0  0  1  1  1  0  0
17  0  1  0  1  0  1  0  0  0  0  ...  1  1  1  1  1  0  1  0  0  0
18  0  1  1  0  1  1  0  1  0  1  ...  1  1  0  1  0  0  0  0  0  0
19  0  0  0  0  0  1  1  2  1  1  ...  0  0  0  0  0  1  0  0  0  0
20  0  0  1  1  1  0  1  1  0  0  ...  1  0  0  1  1  0  1  0  0  0
21  0  1  0  1  1  0  1  1  0  0  ...  1  0  0  0  0  1  0  0  0  0
22  0  0  1  1  0  1  0  2  0  0  ...  1  1  0  0  1  1  1  1  0  0
23  0  0  1  1  1  1  0  2  0  0  ...  1  0  0  1  0  1  0  0  0  0
24  0  1  1  1  1  0  1  0  0  1  ...  1  1  0  0  0  0  0  1  0  0
25  0  1  1  0  0  1  1  0  0  0  ...  0  0  0  1  0  1  1  0  0  0
26  0  1  1  0  0  0  1  1  1  1  ...  1  0  0  0  0  0  0  0  0  0
27  0  1  1  0  1  1  0  0  0  0  ...  1  0  0  1  1  0  1  0  0  0
28  0  1  1  1  0  0  0  2  0  0  ...  0  1  1  0  1  0  1  1  0  0
29  0  0  0  1  0  1  1  0  0  0  ...  0  1  0  1  1  1  1  0  0  0
30  0  0  1  0  0  0  1  0  1  1  ...  1  1  1  0  0  1  0  1  0  0
31  0  0  1  0  0  1  0  1  1  0  ...  0  0  0  0  1  1  1  0  0  0
32  0  1  0  0  1  1  0  0  0  1  ...  1  0  0  1  0  0  0  1  0  0

[33 rows x 22 columns]

In [14]:
kiso_copy

0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15 16 17 18 19 20 21
0   0  1  1  0  0  0  0  1  0  0  ...  1  0  0  0  1  1  1  0  0  0
1   0  1  0  1  1  1  0  0  1  0  ...  0  1  0  0  0  1  0  0  0  0
2   0  0  0  1  2  1  0  1  1  1  ...  0  1  1  1  0  0  0  1  0  0
3   0  0  1  0  1  1  0  0  0  1  ...  1  0  0  0  1  1  1  0  0  0
4   0  1  1  1  0  0  0  1  0  1  ...  1  0  1  1  0  0  1  0  0  0
5   0  0  0  0  0  1  1  1  0  0  ...  0  1  0  1  1  1  0  0  0  0
6   0  1  0  0  0  0  1  1  1  1  ...  0  0  0  0  0  1  1  1  0  0
7   0  0  1  0  0  0  1  1  0  0  ...  0  0  0  0  1  1  1  0  0  0
8   0  0  0  1  0  1  0  1  1  1  ...  0  0  0  0  1  1  0  0  0  0
9   0  0  0  0  1  0  0  2  1  0  ...  1  1  1  0  0  1  1  1  0  0
10  0  1  0  0  1  1  1  0  1  0  ...  1  1  0  0  0  1  0  0  0  0
11  0  0  1  0  0  0  1  0  1  0  ...  1  0  0  0  1  1  1  1  0  0
12  0  0  1  1  1  0  0  0  0  1  ...  1  0  0  1  0  0  0  1  0  0
13  0  0  1  0  1  0  1  0  0  0  ...  1  1  0  0  0  1  1  1  0  0
14  0  1  1  0  1  0  0  2  0  1  ...  0  0  0  0  1  0  1  1  0  0
15  0  1  0  0  1  0  1  1  1  1  ...  1  0  0  0  0  0  0  1  0  0
16  0  0  0  1  1  0  0  0  0  0  ...  1  0  1  0  0  1  1  1  0  0
17  0  1  0  1  0  1  0  0  0  0  ...  1  1  1  1  1  0  1  0  0  0
18  0  1  1  0  1  1  0  1  0  1  ...  1  1  0  1  0  0  0  0  0  0
19  0  0  0  0  0  1  1  2  1  1  ...  0  0  0  0  0  1  0  0  0  0
20  0  0  1  1  1  0  1  1  0  0  ...  1  0  0  1  1  0  1  0  0  0
21  0  1  0  1  1  0  1  1  0  0  ...  1  0  0  0  0  1  0  0  0  0
22  0  0  1  1  0  1  0  2  0  0  ...  1  1  0  0  1  1  1  1  0  0
23  0  0  1  1  1  1  0  2  0  0  ...  1  0  0  1  0  1  0  0  0  0
24  0  1  1  1  1  0  1  0  0  1  ...  1  1  0  0  0  0  0  1  0  0
25  0  1  1  0  0  1  1  0  0  0  ...  0  0  0  1  0  1  1  0  0  0
26  0  1  1  0  0  0  1  1  1  1  ...  1  0  0  0  0  0  0  0  0  0
27  0  1  1  0  1  1  0  0  0  0  ...  1  0  0  1  1  0  1  0  0  0
28  0  1  1  1  0  0  0  2  0  0  ...  0  1  1  0  1  0  1  1  0  0
29  0  0  0  1  0  1  1  0  0  0  ...  0  1  0  1  1  1  1  0  0  0
30  0  0  1  0  0  0  1  0  1  1  ...  1  1  1  0  0  1  0  1  0  0
31  0  0  1  0  0  1  0  1  1  0  ...  0  0  0  0  1  1  1  0  0  0
32  0  1  0  0  1  1  0  0  0  1  ...  1  0  0  1  0  0  0  1  0  0

[33 rows x 22 columns]

In [15]:
kiso_copy2=kiso_copy.iloc[1:,2:]
kiso_copy2=kiso_copy2.reset_index(drop=True)
kiso_copy2

2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21
0   0  1  1  1  0  0  1  0  0  1  0  1  0  0  0  1  0  0  0  0
1   0  1  2  1  0  1  1  1  0  0  0  1  1  1  0  0  0  1  0  0
2   1  0  1  1  0  0  0  1  0  0  1  0  0  0  1  1  1  0  0  0
3   1  1  0  0  0  1  0  1  0  0  1  0  1  1  0  0  1  0  0  0
4   0  0  0  1  1  1  0  0  1  1  0  1  0  1  1  1  0  0  0  0
5   0  0  0  0  1  1  1  1  1  1  0  0  0  0  0  1  1  1  0  0
6   1  0  0  0  1  1  0  0  1  1  0  0  0  0  1  1  1  0  0  0
7   0  1  0  1  0  1  1  1  1  1  0  0  0  0  1  1  0  0  0  0
8   0  0  1  0  0  2  1  0  0  1  1  1  1  0  0  1  1  1  0  0
9   0  0  1  1  1  0  1  0  0  0  1  1  0  0  0  1  0  0  0  0
10  1  0  0  0  1  0  1  0  1  0  1  0  0  0  1  1  1  1  0  0
11  1  1  1  0  0  0  0  1  1  0  1  0  0  1  0  0  0  1  0  0
12  1  0  1  0  1  0  0  0  0  1  1  1  0  0  0  1  1  1  0  0
13  1  0  1  0  0  2  0  1  1  0  0  0  0  0  1  0  1  1  0  0
14  0  0  1  0  1  1  1  1  1  1  1  0  0  0  0  0  0  1  0  0
15  0  1  1  0  0  0  0  0  1  0  1  0  1  0  0  1  1  1  0  0
16  0  1  0  1  0  0  0  0  0  0  1  1  1  1  1  0  1  0  0  0
17  1  0  1  1  0  1  0  1  0  0  1  1  0  1  0  0  0  0  0  0
18  0  0  0  1  1  2  1  1  1  1  0  0  0  0  0  1  0  0  0  0
19  1  1  1  0  1  1  0  0  0  0  1  0  0  1  1  0  1  0  0  0
20  0  1  1  0  1  1  0  0  0  1  1  0  0  0  0  1  0  0  0  0
21  1  1  0  1  0  2  0  0  0  0  1  1  0  0  1  1  1  1  0  0
22  1  1  1  1  0  2  0  0  1  0  1  0  0  1  0  1  0  0  0  0
23  1  1  1  0  1  0  0  1  0  1  1  1  0  0  0  0  0  1  0  0
24  1  0  0  1  1  0  0  0  1  0  0  0  0  1  0  1  1  0  0  0
25  1  0  0  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0
26  1  0  1  1  0  0  0  0  1  1  1  0  0  1  1  0  1  0  0  0
27  1  1  0  0  0  2  0  0  0  0  0  1  1  0  1  0  1  1  0  0
28  0  1  0  1  1  0  0  0  0  1  0  1  0  1  1  1  1  0  0  0
29  1  0  0  0  1  0  1  1  0  1  1  1  1  0  0  1  0  1  0  0
30  1  0  0  1  0  1  1  0  1  0  0  0  0  0  1  1  1  0  0  0
31  0  0  1  1  0  0  0  1  2  1  1  0  0  1  0  0  0  1  0  0

In [16]:
kiso_copy2.loc[3][6]

0

In [17]:
holiday.loc[0][0]

9

In [18]:
holiday

休日数
0    9
1    8
2    9
3    8
4    9
5    9
6   10
7    8
8    9
9    9
10   8
11   9
12   8
13   9
14   9
15  10
16   8
17   9
18   9
19   8
20   9
21   8
22   9
23   9
24  10
25   8
26   9
27  10
28   8
29   9
30  10
31   8
32   9

In [19]:
len(kiso.columns)

24

In [20]:
kiso.columns

RangeIndex(start=0, stop=24, step=1)

In [21]:
#第1世代
kiso_copy=first_gene(kiso,holiday)
kiso_copy

0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15 16 17 18 19 20 21
0   0  1  0  0  0  0  1  1  0  1  ...  1  1  1  0  0  0  1  1  0  0
1   0  0  0  0  0  1  1  0  1  1  ...  1  1  0  1  0  1  0  0  0  0
2   0  0  0  1  2  1  1  1  0  0  ...  0  1  1  1  1  0  0  1  0  0
3   0  0  0  0  0  0  0  1  1  0  ...  0  0  1  0  1  1  0  1  0  0
4   0  1  0  1  0  0  1  1  0  0  ...  0  1  0  0  0  1  0  1  0  0
5   0  0  0  0  0  1  0  1  1  1  ...  1  0  0  1  0  0  1  1  0  0
6   0  0  1  0  1  1  1  1  0  0  ...  0  0  0  1  0  1  1  1  0  0
7   0  1  1  0  0  1  1  0  0  0  ...  0  1  0  0  0  0  1  1  0  0
8   0  1  1  0  1  0  1  1  1  0  ...  1  0  0  0  0  0  0  0  0  0
9   0  1  0  1  0  1  1  2  1  0  ...  0  1  0  0  0  1  0  0  0  0
10  0  0  1  1  0  1  0  0  0  1  ...  1  0  1  1  0  0  0  1  0  0
11  0  1  1  1  0  1  1  0  0  0  ...  0  0  0  1  0  0  1  1  0  0
12  0  1  0  1  1  1  0  0  1  0  ...  1  0  0  0  1  0  1  0  0  0
13  0  0  1  0  0  1  1  1  0  0  ...  0  0  1  1  0  0  1  1  0  0
14  0  0  1  1  0  1  0  2  0  0  ...  0  0  0  0  1  1  1  1  0  0
15  0  1  1  1  0  0  0  0  1  0  ...  1  1  0  1  1  1  1  0  0  0
16  0  0  1  1  1  0  1  1  0  0  ...  0  1  0  0  0  0  1  0  0  0
17  0  0  1  0  0  1  1  0  1  0  ...  0  0  1  0  1  0  1  1  0  0
18  0  0  0  0  1  0  0  1  1  0  ...  0  1  1  1  0  0  1  1  0  0
19  0  0  1  0  0  0  0  2  0  1  ...  0  0  1  0  1  1  1  1  0  0
20  0  1  1  0  0  0  0  0  1  0  ...  1  0  1  1  0  1  0  1  0  0
21  0  0  1  1  0  0  1  1  0  0  ...  0  0  1  0  1  0  0  1  0  0
22  0  0  1  1  0  0  1  2  0  0  ...  0  0  1  1  0  0  1  1  0  0
23  0  0  0  1  1  0  0  2  1  0  ...  0  0  1  1  1  1  0  1  0  0
24  0  1  1  0  1  0  0  0  1  1  ...  0  1  0  0  1  1  1  0  0  0
25  0  1  0  0  1  0  0  0  1  1  ...  1  0  0  1  0  1  0  0  0  0
26  0  0  0  1  0  1  0  1  0  1  ...  1  0  1  0  1  0  0  0  0  0
27  0  0  1  1  0  1  0  1  0  1  ...  1  1  1  0  0  0  0  1  0  0
28  0  0  0  0  0  1  0  2  1  1  ...  0  0  0  1  0  1  1  1  0  0
29  0  0  1  0  1  1  0  1  0  0  ...  1  1  0  0  0  1  1  0  0  0
30  0  0  1  1  0  0  1  1  0  1  ...  0  0  0  1  0  1  0  1  0  0
31  0  1  0  1  1  0  1  0  0  0  ...  0  0  1  0  0  0  1  1  0  0
32  0  0  0  0  0  1  0  0  1  0  ...  1  1  1  0  1  1  0  1  0  0

[33 rows x 22 columns]

In [22]:
#3
#休日数の修正
def holiday_fix(kiso_copy,holiday):

    for k in range(len(kiso_copy)):
            #1か月の日数
        #days=len(kiso.columns)
        days=len(kiso.columns)-2
        if np.count_nonzero(kiso_copy.iloc[k:k+1])!=holiday.loc[k][0]:
            s=np.count_nonzero(kiso_copy.iloc[k:k+1])-holiday.loc[k][0]
            buf=0
            c1=1 if s>0 else 0
            c2=1 if c1==0 else 0
            #増減したい休日日数に達するまでループ
            while buf<abs(s):
                #n=np.random.randint(1,days+1)
                n=np.random.randint(1,days-2)
                if kiso_copy.loc[k][n]==c1:
                    buf+=1
                    #休日を消す
                    kiso_copy.loc[k][n]=c2

    return kiso_copy

In [23]:
kiso_copy

0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15 16 17 18 19 20 21
0   0  1  0  0  0  0  1  1  0  1  ...  1  1  1  0  0  0  1  1  0  0
1   0  0  0  0  0  1  1  0  1  1  ...  1  1  0  1  0  1  0  0  0  0
2   0  0  0  1  2  1  1  1  0  0  ...  0  1  1  1  1  0  0  1  0  0
3   0  0  0  0  0  0  0  1  1  0  ...  0  0  1  0  1  1  0  1  0  0
4   0  1  0  1  0  0  1  1  0  0  ...  0  1  0  0  0  1  0  1  0  0
5   0  0  0  0  0  1  0  1  1  1  ...  1  0  0  1  0  0  1  1  0  0
6   0  0  1  0  1  1  1  1  0  0  ...  0  0  0  1  0  1  1  1  0  0
7   0  1  1  0  0  1  1  0  0  0  ...  0  1  0  0  0  0  1  1  0  0
8   0  1  1  0  1  0  1  1  1  0  ...  1  0  0  0  0  0  0  0  0  0
9   0  1  0  1  0  1  1  2  1  0  ...  0  1  0  0  0  1  0  0  0  0
10  0  0  1  1  0  1  0  0  0  1  ...  1  0  1  1  0  0  0  1  0  0
11  0  1  1  1  0  1  1  0  0  0  ...  0  0  0  1  0  0  1  1  0  0
12  0  1  0  1  1  1  0  0  1  0  ...  1  0  0  0  1  0  1  0  0  0
13  0  0  1  0  0  1  1  1  0  0  ...  0  0  1  1  0  0  1  1  0  0
14  0  0  1  1  0  1  0  2  0  0  ...  0  0  0  0  1  1  1  1  0  0
15  0  1  1  1  0  0  0  0  1  0  ...  1  1  0  1  1  1  1  0  0  0
16  0  0  1  1  1  0  1  1  0  0  ...  0  1  0  0  0  0  1  0  0  0
17  0  0  1  0  0  1  1  0  1  0  ...  0  0  1  0  1  0  1  1  0  0
18  0  0  0  0  1  0  0  1  1  0  ...  0  1  1  1  0  0  1  1  0  0
19  0  0  1  0  0  0  0  2  0  1  ...  0  0  1  0  1  1  1  1  0  0
20  0  1  1  0  0  0  0  0  1  0  ...  1  0  1  1  0  1  0  1  0  0
21  0  0  1  1  0  0  1  1  0  0  ...  0  0  1  0  1  0  0  1  0  0
22  0  0  1  1  0  0  1  2  0  0  ...  0  0  1  1  0  0  1  1  0  0
23  0  0  0  1  1  0  0  2  1  0  ...  0  0  1  1  1  1  0  1  0  0
24  0  1  1  0  1  0  0  0  1  1  ...  0  1  0  0  1  1  1  0  0  0
25  0  1  0  0  1  0  0  0  1  1  ...  1  0  0  1  0  1  0  0  0  0
26  0  0  0  1  0  1  0  1  0  1  ...  1  0  1  0  1  0  0  0  0  0
27  0  0  1  1  0  1  0  1  0  1  ...  1  1  1  0  0  0  0  1  0  0
28  0  0  0  0  0  1  0  2  1  1  ...  0  0  0  1  0  1  1  1  0  0
29  0  0  1  0  1  1  0  1  0  0  ...  1  1  0  0  0  1  1  0  0  0
30  0  0  1  1  0  0  1  1  0  1  ...  0  0  0  1  0  1  0  1  0  0
31  0  1  0  1  1  0  1  0  0  0  ...  0  0  1  0  0  0  1  1  0  0
32  0  0  0  0  0  1  0  0  1  0  ...  1  1  1  0  1  1  0  1  0  0

[33 rows x 22 columns]

In [24]:
holiday

休日数
0    9
1    8
2    9
3    8
4    9
5    9
6   10
7    8
8    9
9    9
10   8
11   9
12   8
13   9
14   9
15  10
16   8
17   9
18   9
19   8
20   9
21   8
22   9
23   9
24  10
25   8
26   9
27  10
28   8
29   9
30  10
31   8
32   9

In [25]:
#4
#希望休を1へ変換
#評価方法
def evalution_function(kiso_copy):
    eva=kiso_copy.replace(2,1)
    score=0

    for k in range(len(eva)):
        #文字列として結合
        x=''.join([str(i) for i in np.array(eva.iloc[k:k+1]).flatten()])
        #5連勤以上の評価
        score+=np.sum([((2-len(i))**2)*-1 for i in x.split('1') if len(i)>=5])
        #print(score)
        #3連休以上の評価
        score+=np.sum([((1-len(i))**2)*-1 for i in x.split('0') if len(i)>=3])
        #print(score)
        #飛び石連休の評価
        score+=-10*(len(x.split('101'))-1)
        #print(score)
    #出勤数の評価
    score+=np.sum([abs(len(eva)*0.7-(len(eva)-np.sum(eva[k])))*-4 for k in eva.columns])
    return score
    #print(score)

In [26]:
#評価
score=evalution_function(kiso_copy)
score

-1451.3999999999999

In [27]:
kiso_copy

0  1  2  3  4  5  6  7  8  9   ... 12 13 14 15 16 17 18 19 20 21
0   0  1  0  0  0  0  1  1  0  1  ...  1  1  1  0  0  0  1  1  0  0
1   0  0  0  0  0  1  1  0  1  1  ...  1  1  0  1  0  1  0  0  0  0
2   0  0  0  1  2  1  1  1  0  0  ...  0  1  1  1  1  0  0  1  0  0
3   0  0  0  0  0  0  0  1  1  0  ...  0  0  1  0  1  1  0  1  0  0
4   0  1  0  1  0  0  1  1  0  0  ...  0  1  0  0  0  1  0  1  0  0
5   0  0  0  0  0  1  0  1  1  1  ...  1  0  0  1  0  0  1  1  0  0
6   0  0  1  0  1  1  1  1  0  0  ...  0  0  0  1  0  1  1  1  0  0
7   0  1  1  0  0  1  1  0  0  0  ...  0  1  0  0  0  0  1  1  0  0
8   0  1  1  0  1  0  1  1  1  0  ...  1  0  0  0  0  0  0  0  0  0
9   0  1  0  1  0  1  1  2  1  0  ...  0  1  0  0  0  1  0  0  0  0
10  0  0  1  1  0  1  0  0  0  1  ...  1  0  1  1  0  0  0  1  0  0
11  0  1  1  1  0  1  1  0  0  0  ...  0  0  0  1  0  0  1  1  0  0
12  0  1  0  1  1  1  0  0  1  0  ...  1  0  0  0  1  0  1  0  0  0
13  0  0  1  0  0  1  1  1  0  0  ...  0  0  1  1  0  0  1  1  0  0
14  0  0  1  1  0  1  0  2  0  0  ...  0  0  0  0  1  1  1  1  0  0
15  0  1  1  1  0  0  0  0  1  0  ...  1  1  0  1  1  1  1  0  0  0
16  0  0  1  1  1  0  1  1  0  0  ...  0  1  0  0  0  0  1  0  0  0
17  0  0  1  0  0  1  1  0  1  0  ...  0  0  1  0  1  0  1  1  0  0
18  0  0  0  0  1  0  0  1  1  0  ...  0  1  1  1  0  0  1  1  0  0
19  0  0  1  0  0  0  0  2  0  1  ...  0  0  1  0  1  1  1  1  0  0
20  0  1  1  0  0  0  0  0  1  0  ...  1  0  1  1  0  1  0  1  0  0
21  0  0  1  1  0  0  1  1  0  0  ...  0  0  1  0  1  0  0  1  0  0
22  0  0  1  1  0  0  1  2  0  0  ...  0  0  1  1  0  0  1  1  0  0
23  0  0  0  1  1  0  0  2  1  0  ...  0  0  1  1  1  1  0  1  0  0
24  0  1  1  0  1  0  0  0  1  1  ...  0  1  0  0  1  1  1  0  0  0
25  0  1  0  0  1  0  0  0  1  1  ...  1  0  0  1  0  1  0  0  0  0
26  0  0  0  1  0  1  0  1  0  1  ...  1  0  1  0  1  0  0  0  0  0
27  0  0  1  1  0  1  0  1  0  1  ...  1  1  1  0  0  0  0  1  0  0
28  0  0  0  0  0  1  0  2  1  1  ...  0  0  0  1  0  1  1  1  0  0
29  0  0  1  0  1  1  0  1  0  0  ...  1  1  0  0  0  1  1  0  0  0
30  0  0  1  1  0  0  1  1  0  1  ...  0  0  0  1  0  1  0  1  0  0
31  0  1  0  1  1  0  1  0  0  0  ...  0  0  1  0  0  0  1  1  0  0
32  0  0  0  0  0  1  0  0  1  0  ...  1  1  1  0  1  1  0  1  0  0

[33 rows x 22 columns]

In [28]:
holiday

休日数
0    9
1    8
2    9
3    8
4    9
5    9
6   10
7    8
8    9
9    9
10   8
11   9
12   8
13   9
14   9
15  10
16   8
17   9
18   9
19   8
20   9
21   8
22   9
23   9
24  10
25   8
26   9
27  10
28   8
29   9
30  10
31   8
32   9

In [29]:
#関数化
#1エクセル読み込み
kiso,holiday=read_excel()
#2第1世代
kiso_copy=first_gene(kiso,holiday)
#3休日数の修正
kiso_copy=holiday_fix(kiso_copy,holiday)
#4評価
score=evalution_function(kiso_copy)
score

-1504.3999999999999

In [30]:
holiday

休日数
0    9
1    8
2    9
3    8
4    9
5    9
6   10
7    8
8    9
9    9
10   8
11   9
12   8
13   9
14   9
15  10
16   8
17   9
18   9
19   8
20   9
21   8
22   9
23   9
24  10
25   8
26   9
27  10
28   8
29   9
30  10
31   8
32   9

In [31]:
#6遺伝的アルゴリズム

In [32]:
import numpy as np
import pandas as pd
from random import random
from array import array

#def read_excel():
    #Excel読み込み
#    df=pd.read_excel('iden.xlsm',sheet_name='Sheet1')
#一様交叉,ep=0.5,sd=0.05
def crossover(ep,sd,p1,p2):
    #1か月の日数
    days=len(p1.columns)
    #1次元化
    p1=np.array(p1).flatten()
    p2=np.array(p2).flatten()
    #子の変数
    ch1=[]
    ch2=[]
    for p1_,p2_ in zip(p1,p2):
        x = True if ep >random() else False
        if x==True:
            ch1.append(p1_)
            ch2.append(p2_)
        else:
            ch1.append(p2_)
            ch2.append(p1_)
    #突然変異
    ch1,ch2=mutation(sd,np.array(ch1).flatten(),np.array(ch2).flatten())
    #pandasに変換
    ch1=pd.DataFrame(ch1.reshape(int(len(ch1)/days),days))
    ch2=pd.DataFrame(ch2.reshape(int(len(ch2)/days),days))
    #列名の変更
    ch1.columns=[i+1 for i in range(len(ch1.columns))]
    ch2.columns=[i+1 for i in range(len(ch2.columns))]
    return ch1,ch2
#突然変異
def mutation(sd,ch1,ch2):
    x = True if sd>random() else False
    if x==True:
        rand=np.random.permutation([i for i in range(len(ch1))])
        #遺伝子の10％を変異させる
        #並び換えた先頭10％
        rand=rand[:int(len(ch1)//10)]
        for i in rand:
            #1なら0,0なら1
            if ch1[i]==1:
                ch1[i]==0

            if ch1[i]==0:
                ch1[i]==1
                #ch2も同じことをする。
    x=True if sd>random() else False
    if x==True:
        rand=np.random.permutation([i for i in range(len(ch1))])
        #並び換えた先頭10％
        rand=rand[:int(len(ch1)//10)]
        for i in rand:
            #1なら0,0なら1
            if ch2[i]==1:
                ch2[i]==0
            if ch2[i]==0:
                ch2[i]==1

    return ch1,ch2


In [33]:
#7全体

In [34]:
#遺伝的アルゴリズム
#エクセル読み込み
kiso,holiday=read_excel()
#親の保存
parent=[]
for i in range(100):
    #第1世代
    kiso_copy=first_gene(kiso,holiday)
    #休日数の修正
    kiso_copy=holiday_fix(kiso_copy,holiday)
    #parent.append(kiso_copy)
    #評価
    score=evalution_function(kiso_copy)
    #第1世代を格納
    parent.append([score,kiso_copy])
#上位個体数
elite_length=20
#世代数
gene_length=50

#一様交叉確立
ep=0.5
#突然変異確立
sd=0.05

#一様交叉
#ch1 = pd.DataFrame(ch1)
#ch2 = pd.DataFrame(ch2)
#ch1,ch2=crossover(ep,sd,parent[0],parent[1])
#休日数変更
#ch1=holiday_fix(ch1,holiday)
#ch2=holiday_fix(ch2,holiday)

for i in range(gene_length):
    #点数で並び換え
    parent = sorted(parent, key=lambda x: -x[0])
    #parent=sorted(np.array(parent), key=lambda x:-x[0])
    #parent=sorted(np.array(parent[0]).flatten(), key=lambda x:-x[0])
    #p1=np.array(parent[0]).flatten()
    #上位個体を選別
    parent=parent[:elite_length]
    #各世代
    print('第'+str(i+1)+'世代')

    #最高得点の更新
    #if i ==0 or top[0]<parent[0][0]:
    if i ==0:
        top=parent[0]
            #各世代の最高得点の表示
        print(top[0])
        print(np.array(top[1]))
    else:
        if top[0]>parent[0][0]:
            parent.append(top)
            #各世代の最高得点の表示
            print(top[0])
            print(np.array(top[1]))
        else:
            top=parent[0]
            #各世代の最高得点の表示
            print(parent[0][0])
            print(np.array(parent[0][1]))

    #各世代
    #print('第'+str(i+1)+'世代')
    #各世代の最高得点の表示
    #print(top[0])
    #print(np.array(top[1]))

    #子世代
    children=[]
    #遺伝子操作
    for k1,v1 in enumerate(parent):
        for k2,v2 in enumerate(parent):
            if k1<k2:
                #一様交叉
                ch1,ch2=crossover(ep,sd,v1[1],v2[1])
                #休日数変更
                ch1=holiday_fix(ch1,holiday)
                ch2=holiday_fix(ch2,holiday)
                #評価
                score1=evalution_function(ch1)
                score2=evalution_function(ch2)
                #子孫を格納
                children.append([score1,ch1])
                children.append([score2,ch2])

    #子を親にコピー
    parent=children.copy()

#最強個体の保存
x=top[1].replace(1,'〇').replace(2,'◎').replace(0,'')
x.to_excel('/content/drive/MyDrive/Colab Notebooks/iden/o_ma_shift4.xlsx')


第1世代
-1315.3999999999999
[[0 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 2 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0]
 [0 1 1 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 0 0]
 [0 0 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0]
 [0 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0]
 [0 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 0 0]
 [0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]
 [0 0 0 0 1 0 1 2 0 0 0 1 0 0 1 1 1 1 0 1 0 0]
 [0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0]
 [0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0]
 [0 1 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 0 1 1 2 0 0 1 1 1 0 0 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0]
 [0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 0]
 [0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 2 0 1 0 0 1 0 0 1 1 0 0 1 0 0]
 [0 0 1 0 1 1 1 1 1 0 0 0 1 1 0 0 0